from __future__ import annotations

import json
import time
from typing import Any

from openai import OpenAI, OpenAIError

from .config import get_settings

_SYSTEM_PROMPT = (
    "You are PlanPlain, an expert Terraform/OpenTofu infrastructure analyst. "
    "Your job is to make infrastructure changes understandable to any engineer, not just Terraform experts. "
    "Be specific and reference actual resource names and values. "
    "IMPORTANT: Respond with valid JSON only."
)


def _build_prompt(changes_summary: str, heuristic_flags: str, metadata: dict[str, Any]) -> str:
    return f"""Analyze this Terraform plan and respond with JSON containing exactly these fields:

{{
  "summary": "2-4 sentence plain-English summary of what's changing and why it matters.",
  "risk_flags": [
    {{ "severity": "HIGH|MED|LOW", "resource": "resource.address", "message": "Why this is risky" }}
  ],
  "reviewer_checklist": [
    "Specific, actionable item a reviewer should verify"
  ]
}}

## Plan Overview
- Terraform version: {metadata.get("terraform_version")}
- Resources created: {metadata.get("resources_created")}
- Resources updated: {metadata.get("resources_updated")}
- Resources destroyed: {metadata.get("resources_destroyed")}
- Resources replaced: {metadata.get("resources_replaced")}
- Total changes: {metadata.get("resources_total")}

## Resource Changes
{changes_summary or 'No changes detected'}

## Detected Risk Patterns
{heuristic_flags or 'None detected by heuristics'}

Rules:
- For risk_flags: only add flags the heuristics missed; don't duplicate existing ones.
- For reviewer_checklist: 3-8 specific items. Include "Confirm this plan was generated from the correct branch/workspace" as the last item.
- Be direct and concise.
"""


def _merge_risk_flags(heuristic_flags: list[dict[str, Any]], ai_flags: list[dict[str, Any]]) -> list[dict[str, Any]]:
    merged = list(heuristic_flags)
    existing = {f"{f.get('resource')}:{f.get('severity')}" for f in heuristic_flags}

    for flag in ai_flags:
        key = f"{flag.get('resource')}:{flag.get('severity')}"
        if key not in existing:
            merged.append(flag)
            existing.add(key)

    order = {"HIGH": 0, "MED": 1, "LOW": 2}
    merged.sort(key=lambda f: order.get(f.get("severity", "LOW"), 99))
    return merged


def _generate_pr_markdown(summary: str, risk_flags: list[dict[str, Any]], checklist: list[str], metadata: dict[str, Any]) -> str:
    lines = [
        "## Terraform Plan Analysis",
        "",
        f"> Analyzed by [PlanPlain](https://planplain.polsia.app) | {metadata.get('resources_total', 0)} resource(s) changing",
        "",
        "### Summary",
        "",
        summary,
        "",
        "### Changes",
        "",
        "| Action | Count |",
        "|--------|-------|",
    ]

    if metadata.get("resources_created", 0) > 0:
        lines.append(f"| :green_circle: Create | {metadata['resources_created']} |")
    if metadata.get("resources_updated", 0) > 0:
        lines.append(f"| :yellow_circle: Update | {metadata['resources_updated']} |")
    if metadata.get("resources_destroyed", 0) > 0:
        lines.append(f"| :red_circle: Destroy | {metadata['resources_destroyed']} |")
    if metadata.get("resources_replaced", 0) > 0:
        lines.append(f"| :orange_circle: Replace | {metadata['resources_replaced']} |")

    lines.append("")

    if risk_flags:
        label = ":rotating_light:" if any(f.get("severity") == "HIGH" for f in risk_flags) else ":warning:"
        lines.extend([f"### Risk Flags {label}", ""])
        for flag in risk_flags:
            severity = flag.get("severity", "LOW")
            icon = ":red_circle:" if severity == "HIGH" else ":yellow_circle:" if severity == "MED" else ":white_circle:"
            lines.append(f"- {icon} **{severity}** `{flag.get('resource', 'unknown')}`: {flag.get('message', '')}")
        lines.append("")

    if checklist:
        lines.extend(["### Reviewer Checklist", ""])
        for item in checklist:
            lines.append(f"- [ ] {item}")
        lines.append("")

    lines.extend(["---", "*Generated by [PlanPlain](https://planplain.polsia.app)*"])
    return "\n".join(lines)


def analyze_plan(parsed_plan: dict[str, Any]) -> dict[str, Any]:
    settings = get_settings()
    changes = parsed_plan.get("changes", [])
    risk_flags = parsed_plan.get("risk_flags", [])
    metadata = parsed_plan.get("metadata", {})

    changes_lines: list[str] = []
    for change in changes:
        line = [f"{change.get('action', 'unknown').upper()}: {change.get('address', 'unknown')} ({change.get('provider', 'unknown')})"]
        fields = change.get("changed_fields", [])
        if fields:
            for field in fields[:8]:
                line.append(f"  - {field.get('field')}: {field.get('from')} -> {field.get('to')}")
            if len(fields) > 8:
                line.append(f"  ... and {len(fields) - 8} more fields")
        changes_lines.append("\n".join(line))

    changes_summary = "\n\n".join(changes_lines)
    heuristic_flags = "\n".join(
        f"[{flag.get('severity', 'LOW')}] {flag.get('resource', 'unknown')}: {flag.get('message', '')}"
        for flag in risk_flags
    )

    prompt = _build_prompt(changes_summary, heuristic_flags, metadata)
    client = OpenAI(api_key=settings.openrouter_api_key, base_url=settings.openrouter_base_url)

    started = time.time()
    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            max_tokens=4000,
            response_format={"type": "json_object"},
        )
    except OpenAIError as exc:
        raise RuntimeError(f"AI request failed: {exc}") from exc

    content = response.choices[0].message.content if response.choices else None
    if not content:
        raise RuntimeError("AI returned empty response")

    try:
        parsed = json.loads(content)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"AI returned invalid JSON: {exc}") from exc
    merged_flags = _merge_risk_flags(risk_flags, parsed.get("risk_flags", []))
    checklist = parsed.get("reviewer_checklist", [])
    summary = parsed.get("summary", "No summary generated")

    return {
        "summary": summary,
        "risk_flags": merged_flags,
        "reviewer_checklist": checklist,
        "pr_markdown": _generate_pr_markdown(summary, merged_flags, checklist, metadata),
        "_ai_metadata": {
            "processing_time_ms": int((time.time() - started) * 1000),
            "tokens_used": getattr(response.usage, "total_tokens", 0) if response.usage else 0,
        },
    }
