/**
 * POST /api/analyze
 *
 * Core endpoint: accepts Terraform plan JSON, returns structured analysis.
 */
const express = require('express');
const crypto = require('crypto');
const { parsePlan, PlanParseError } = require('../services/plan-parser');
const { analyzePlan } = require('../services/ai-analyzer');

function createAnalyzeRouter(pool) {
  const router = express.Router();

  router.post('/', async (req, res) => {
    const startTime = Date.now();

    // Capture request size from header or body serialization
    const requestSizeBytes = parseInt(req.headers['content-length'] || '0', 10) ||
      Buffer.byteLength(JSON.stringify(req.body || {}));

    // Track response state for unified logging at the end
    let riskLevel = null;
    let resourceCount = null;
    let errorMsg = null;

    try {
      // Validate input
      const planJson = req.body;
      if (!planJson || typeof planJson !== 'object' || Object.keys(planJson).length === 0) {
        errorMsg = 'INVALID_INPUT';
        const processingTime = Date.now() - startTime;
        logApiRequest(pool, {
          apiKeyHash: req.apiKey?.key_hash,
          requestSizeBytes,
          responseTimeMs: processingTime,
          riskLevel: null,
          resourceCount: null,
          error: errorMsg,
        }).catch(err => console.error('[stats] Failed to log api_request:', err.message));
        return res.status(400).json({
          success: false,
          error: 'INVALID_INPUT',
          message: 'Request body must be a non-empty JSON object. Send the output of: terraform show -json tfplan',
        });
      }

      // Parse the Terraform plan
      let parsed;
      try {
        parsed = parsePlan(planJson);
      } catch (err) {
        if (err instanceof PlanParseError) {
          errorMsg = `INVALID_PLAN: ${err.message}`;
          const processingTime = Date.now() - startTime;
          logApiRequest(pool, {
            apiKeyHash: req.apiKey?.key_hash,
            requestSizeBytes,
            responseTimeMs: processingTime,
            riskLevel: null,
            resourceCount: null,
            error: errorMsg,
          }).catch(e => console.error('[stats] Failed to log api_request:', e.message));
          return res.status(422).json({
            success: false,
            error: 'INVALID_PLAN',
            message: err.message,
          });
        }
        throw err;
      }

      // Handle empty plans (no changes)
      if (parsed.changes.length === 0) {
        const processingTime = Date.now() - startTime;
        console.log(`[analyze] key=${req.apiKey?.key_prefix || 'unknown'} risk=none resources=0 time=${processingTime}ms size=${requestSizeBytes}B`);
        logApiRequest(pool, {
          apiKeyHash: req.apiKey?.key_hash,
          requestSizeBytes,
          responseTimeMs: processingTime,
          riskLevel: 'NONE',
          resourceCount: 0,
          error: null,
        }).catch(err => console.error('[stats] Failed to log api_request:', err.message));
        const emptyResult = {
          success: true,
          analysis: {
            summary: 'No infrastructure changes detected. The plan is empty — your infrastructure matches the desired state.',
            risk_flags: [],
            reviewer_checklist: ['Confirm this is the expected result (no changes needed)'],
            pr_markdown: '## Terraform Plan Analysis\n\n> No changes detected. Infrastructure is up to date.\n\n---\n*Generated by [PlanPlain](https://dev.plainplan.click)*',
          },
          metadata: parsed.metadata,
        };
        return res.json(emptyResult);
      }

      // Run AI analysis
      let analysis;
      try {
        analysis = await analyzePlan(parsed);
      } catch (err) {
        console.error('AI analysis error:', err.message);

        // Fall back to heuristic-only analysis if AI fails
        analysis = {
          summary: buildFallbackSummary(parsed),
          risk_flags: parsed.riskFlags,
          reviewer_checklist: buildFallbackChecklist(parsed),
          pr_markdown: buildFallbackMarkdown(parsed),
          _ai_metadata: { processing_time_ms: 0, tokens_used: 0, fallback: true },
        };
      }

      const processingTime = Date.now() - startTime;
      riskLevel = parsed.metadata.max_risk_level || 'LOW';
      resourceCount = parsed.metadata.resources_total || 0;

      // Console log for Render log visibility
      console.log(`[analyze] key=${req.apiKey?.key_prefix || 'unknown'} risk=${riskLevel} resources=${resourceCount} time=${processingTime}ms size=${requestSizeBytes}B`);

      // Log the analysis to analysis_logs (existing, detailed)
      const planHash = crypto.createHash('sha256')
        .update(JSON.stringify(planJson).slice(0, 10000))
        .digest('hex')
        .slice(0, 16);

      logAnalysis(pool, {
        apiKeyId: req.apiKey?.id,
        planHash,
        metadata: parsed.metadata,
        maxRiskLevel: parsed.metadata.max_risk_level,
        processingTimeMs: processingTime,
        tokensUsed: analysis._ai_metadata?.tokens_used || 0,
      }).catch(err => console.error('Failed to log analysis:', err.message));

      // Log to api_requests (new, lightweight metrics table)
      logApiRequest(pool, {
        apiKeyHash: req.apiKey?.key_hash,
        requestSizeBytes,
        responseTimeMs: processingTime,
        riskLevel,
        resourceCount,
        error: null,
      }).catch(err => console.error('[stats] Failed to log api_request:', err.message));

      // Return the analysis
      res.json({
        success: true,
        analysis: {
          summary: analysis.summary,
          risk_flags: analysis.risk_flags,
          reviewer_checklist: analysis.reviewer_checklist,
          pr_markdown: analysis.pr_markdown,
        },
        metadata: {
          ...parsed.metadata,
          processing_time_ms: processingTime,
        },
      });

    } catch (err) {
      console.error('Analyze endpoint error:', err);
      const processingTime = Date.now() - startTime;
      errorMsg = err.message || 'ANALYSIS_FAILED';

      console.log(`[analyze] key=${req.apiKey?.key_prefix || 'unknown'} risk=error time=${processingTime}ms error="${errorMsg}"`);

      // Log the error to api_requests
      logApiRequest(pool, {
        apiKeyHash: req.apiKey?.key_hash,
        requestSizeBytes,
        responseTimeMs: processingTime,
        riskLevel: null,
        resourceCount: null,
        error: errorMsg,
      }).catch(e => console.error('[stats] Failed to log api_request:', e.message));

      res.status(500).json({
        success: false,
        error: 'ANALYSIS_FAILED',
        message: 'Internal error during plan analysis. Please try again.',
        processing_time_ms: processingTime,
      });
    }
  });

  return router;
}

/**
 * Log to api_requests table — lightweight metrics row per request
 */
async function logApiRequest(pool, data) {
  await pool.query(
    `INSERT INTO api_requests (api_key_hash, request_size_bytes, response_time_ms, risk_level, resource_count, error)
     VALUES ($1, $2, $3, $4, $5, $6)`,
    [
      data.apiKeyHash || null,
      data.requestSizeBytes || null,
      data.responseTimeMs || null,
      data.riskLevel || null,
      data.resourceCount !== undefined ? data.resourceCount : null,
      data.error || null,
    ]
  );
}

/**
 * Log analysis to database for usage tracking
 */
async function logAnalysis(pool, data) {
  await pool.query(
    `INSERT INTO analysis_logs (api_key_id, plan_hash, resources_total, resources_created, resources_updated, resources_destroyed, resources_replaced, max_risk_level, processing_time_ms, ai_tokens_used)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)`,
    [
      data.apiKeyId,
      data.planHash,
      data.metadata.resources_total,
      data.metadata.resources_created,
      data.metadata.resources_updated,
      data.metadata.resources_destroyed,
      data.metadata.resources_replaced,
      data.maxRiskLevel,
      data.processingTimeMs,
      data.tokensUsed,
    ]
  );
}

/**
 * Fallback summary when AI is unavailable
 */
function buildFallbackSummary(parsed) {
  const m = parsed.metadata;
  const parts = [];

  if (m.resources_created > 0) parts.push(`creating ${m.resources_created} resource(s)`);
  if (m.resources_updated > 0) parts.push(`updating ${m.resources_updated} resource(s)`);
  if (m.resources_destroyed > 0) parts.push(`destroying ${m.resources_destroyed} resource(s)`);
  if (m.resources_replaced > 0) parts.push(`replacing ${m.resources_replaced} resource(s)`);

  const summary = `This plan includes ${m.resources_total} change(s): ${parts.join(', ')}.`;

  if (m.max_risk_level === 'HIGH') {
    return summary + ' HIGH risk flags detected — review carefully before applying.';
  }
  return summary;
}

/**
 * Fallback checklist when AI is unavailable
 */
function buildFallbackChecklist(parsed) {
  const items = [];

  if (parsed.metadata.resources_destroyed > 0) {
    items.push('Verify all resource destroys are intentional and data has been backed up');
  }
  if (parsed.metadata.resources_replaced > 0) {
    items.push('Confirm replaced resources can tolerate recreation (check for data loss)');
  }
  if (parsed.riskFlags.some(f => f.severity === 'HIGH')) {
    items.push('Review all HIGH severity risk flags before approving');
  }

  items.push('Confirm this plan was generated from the correct branch/workspace');
  items.push('Verify the Terraform state is up to date (no drift)');

  return items;
}

/**
 * Fallback markdown when AI is unavailable
 */
function buildFallbackMarkdown(parsed) {
  const lines = ['## Terraform Plan Analysis', ''];
  lines.push(`> ${parsed.metadata.resources_total} resource(s) changing`);
  lines.push('');
  lines.push(buildFallbackSummary(parsed));
  lines.push('');

  if (parsed.riskFlags.length > 0) {
    lines.push('### Risk Flags');
    lines.push('');
    for (const flag of parsed.riskFlags) {
      const icon = flag.severity === 'HIGH' ? ':red_circle:' : flag.severity === 'MED' ? ':yellow_circle:' : ':white_circle:';
      lines.push(`- ${icon} **${flag.severity}** \`${flag.resource}\`: ${flag.message}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [PlanPlain](https://dev.plainplan.click)*');
  return lines.join('\n');
}

module.exports = { createAnalyzeRouter, logApiRequest };
