#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"
PREFIX="${PLAINPLAN_AWS_CONFIG_PREFIX:-plainplan/prod}"
AWS_REGION_VALUE="${AWS_REGION:-}"

if ! command -v aws >/dev/null 2>&1; then
  echo "[sync] aws CLI is required"
  exit 1
fi

usage() {
  cat <<USAGE
Usage: scripts/sync_env_from_aws.sh [options]

Options:
  --env-file PATH     Output env file (default: .env)
  --prefix NAME       Secret/parameter prefix (default: plainplan/prod)
  --region REGION     AWS region override (default: AWS_REGION env or AWS profile)
  --help              Show this help

Lookup strategy per key:
  1) AWS Secrets Manager secret: <prefix>/<KEY>
  2) SSM parameter:              /<prefix>/<KEY> (or <prefix>/<KEY>)

Example:
  scripts/sync_env_from_aws.sh --prefix plainplan/prod --region us-east-1
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file)
      ENV_FILE="$2"
      shift 2
      ;;
    --prefix)
      PREFIX="$2"
      shift 2
      ;;
    --region)
      AWS_REGION_VALUE="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "[sync] Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

AWS_ARGS=()
if [[ -n "$AWS_REGION_VALUE" ]]; then
  AWS_ARGS+=(--region "$AWS_REGION_VALUE")
fi

SECRETS_KEYS=(
  OPENROUTER_API_KEY
  OPENROUTER_BASE_URL
  STATS_SECRET
  DATABASE_URL
  ACM_CERTIFICATE_ARN
  TF_STATE_BUCKET
  TF_STATE_REGION
  TF_LOCK_TABLE
)

PARAM_KEYS=(
  AWS_REGION
  PROJECT_NAME
  ENVIRONMENT
  CUSTOM_DOMAIN_NAME
  TF_STATE_KEY
  ENABLE_AURORA_SERVERLESS
  AURORA_DATABASE_NAME
  AURORA_ENGINE_VERSION
  AURORA_MIN_CAPACITY
  AURORA_MAX_CAPACITY
)

fetch_secret_value() {
  local key="$1"
  local name="${PREFIX}/${key}"

  aws "${AWS_ARGS[@]}" secretsmanager get-secret-value \
    --secret-id "$name" \
    --query SecretString \
    --output text 2>/dev/null || return 1
}

fetch_parameter_value() {
  local key="$1"
  local name1="/${PREFIX}/${key}"
  local name2="${PREFIX}/${key}"

  aws "${AWS_ARGS[@]}" ssm get-parameter \
    --name "$name1" \
    --with-decryption \
    --query 'Parameter.Value' \
    --output text 2>/dev/null || \
  aws "${AWS_ARGS[@]}" ssm get-parameter \
    --name "$name2" \
    --with-decryption \
    --query 'Parameter.Value' \
    --output text 2>/dev/null || return 1
}

declare -A VALUES
MISSING=()

for key in "${SECRETS_KEYS[@]}"; do
  if value="$(fetch_secret_value "$key")"; then
    VALUES["$key"]="$value"
    continue
  fi
  if value="$(fetch_parameter_value "$key")"; then
    VALUES["$key"]="$value"
    continue
  fi
  MISSING+=("$key")
done

for key in "${PARAM_KEYS[@]}"; do
  if value="$(fetch_secret_value "$key")"; then
    VALUES["$key"]="$value"
    continue
  fi
  if value="$(fetch_parameter_value "$key")"; then
    VALUES["$key"]="$value"
    continue
  fi
  MISSING+=("$key")
done

mkdir -p "$(dirname "$ENV_FILE")"

if [[ -f "$ENV_FILE" ]]; then
  cp "$ENV_FILE" "${ENV_FILE}.bak"
  echo "[sync] Backed up existing env file to ${ENV_FILE}.bak"
fi

{
  echo "# Generated by scripts/sync_env_from_aws.sh"
  echo "# Prefix: ${PREFIX}"
  echo

  for key in "${PARAM_KEYS[@]}"; do
    if [[ -n "${VALUES[$key]+x}" ]]; then
      printf '%s=%q\n' "$key" "${VALUES[$key]}"
    fi
  done

  echo

  for key in "${SECRETS_KEYS[@]}"; do
    if [[ -n "${VALUES[$key]+x}" ]]; then
      printf '%s=%q\n' "$key" "${VALUES[$key]}"
    fi
  done
} > "$ENV_FILE"

echo "[sync] Wrote $ENV_FILE"

if [[ ${#MISSING[@]} -gt 0 ]]; then
  echo "[sync] Missing keys (not found in Secrets Manager or SSM under ${PREFIX}):"
  printf '  - %s\n' "${MISSING[@]}"
  echo "[sync] Missing entries are optional unless required by your selected deploy mode."
fi
